### ISSUE TITLE
Error compiling  of elsevierbook-project-template

### ISSUE THREAD

**Issue by Kyrchei** [vtex-soft/texsupport.elsevier-book#43]
Hi,
I downloaded the latest version of elsevierbook-project-template, unzipped, and compiled it.
Compilation failed with the following error message:
Sorry, but miktex-makepk did not succeed.
The log file hopefully contains the information to get MiKTeX going again:
C:\Users\User\AppData\Local\MiKTeX\miktex\log\miktex-makepk.log
 )
!pdfTeX error: pdflatex.exe (file ntx-Regular-tlf-t1): Font ntx-Regular-tlf-t1 
at 480 not found
 ==> Fatal error occurred, no output PDF file produced!

**Comment by dgalcius** [comment]
Hi, it does compile with the pdfTeX 3.141592653-2.6-1.40.26 (TeX Live 2024) compiler on my box.
Please check your distribution is up-to-date and you have "newtxtext" package installed.

**Comment by Kyrchei** [comment]
Many thanks! After upgrading Latex, all is working!

**Comment by dgalcius** [comment]
Thank you. Closing the issue.
